### ISSUE TITLE
[ERROR] Authentication Documentation Clarity

### ISSUE THREAD

**Issue by MarkMoretto** [discuitnet/docs#13]
### Where is the error?

Couple quick (probably easily resolvable) items:

1. For the getting started / authentication page [here](https://docs.discuit.net/authentication), the example return headers are given as follows:

```sh
cache-control: no-store
content-type: application/json; charset=UTF-8
csrf-token: FcVgW9FZD8w3iptTeh-Nm3cWm4QjVXYulKjqMWjSJkg=
set-cookie: SID=GyzghHpzr3vOdUG2pOoEeqRBFKwbVWBw5Ovy; Path=/; Expires=Mon, 03 Mar 2025 17:48:50 GMT; HttpOnly; Secure; SameSite=Lax
set-cookie: csrftoken=FcVgW9FZD8w3iptTeh-Nm3cWm4QjVXYulKjqMWjSJkg=; Path=/
date: Fri, 08 Mar 2024 17:48:50 GMT
```

Then, an example request is given as follows [with light editing for readability]:

```sh
curl -X POST \
-H 'Cookie: SID=aVVdZDQLCaDUFnMEwKwpbzwoNVnytESJNRVI' \
-H 'X-Csrf-Token: ciSk6IDY7rQ1pHu9yueb2TXUjJQU8r1pKjisA3S7Px0=' \
-d '{"username":"neo","password":"whatever"}' \
"http://discuit.net/api/_login"
```

Is there a way to merge the two sets of data so that one might logically flow to the next?  My guess would be that, for the example header response, the login call might look like the following:

```sh
curl -X POST \
-H 'Cookie: SID=GyzghHpzr3vOdUG2pOoEeqRBFKwbVWBw5Ovy' \
-H 'X-Csrf-Token: FcVgW9FZD8w3iptTeh-Nm3cWm4QjVXYulKjqMWjSJkg=' \
-d '{"username":"neo","password":"whatever"}' \
"http://discuit.net/api/_login"
```

2. As a casual API user, the example header response has the key `set-cookie` twice.  Is that a typo or should users expect to handle identical keys?  I would guess that those values would merge until a single key is left, correct?

### Would you like to work on this?

- [ ] I would like to work on this.

**Comment by noClaps** [comment]
I'll update the example to use the same token and cookie.

> As a casual API user, the example header response has the key set-cookie twice. Is that a typo or should users expect to handle identical keys? I would guess that those values would merge until a single key is left, correct?

I've copied and pasted the response that I get when running `curl` with the `/_initial` endpoint. In the response, the `set-cookie` key is there twice. You'd have to ask previnder for why that is, and whether it's a bug or not. I'll close this issue once the token and cookie change has been merged, and you can reopen it or open a new issue if there's any updates to the second question.

**Comment by MarkMoretto** [comment]
Just a quick note: Here's a parser to check if a session cookie is set and sets it, if not.  Runs from bash, not sure about other non-shopt terminals.

```sh
shopt -s extglob
MY_SESS_COOKIE=
MY_SESS_CSRF=
while IFS=':' read k v; do
    # Trim whitespace.
    v=${v##+([[:space:]])}
    v=${v%%+([[:space:]])}

    case "$k" in
        csrf-token)
            MY_SESS_CSRF="$v"
        ;;
        set-cookie)
            # Check if variable is unset.
            if [[ -z "${MY_SESS_COOKIE}" ]]; then
                # Capture first "Set-Cookie" value token via `cut` and index selection.
                MY_SESS_COOKIE=$(echo "$v" | cut -d ';' -f 1)
            fi
        ;;
    esac
done < <(curl -X GET -I "https://discuit.net/api/_initial" -s)

printf 'Cookie: %s\nCsrf: %s\n' "${MY_SESS_COOKIE}" "${MY_SESS_CSRF}"
```

**Comment by noClaps** [comment]
This is really cool, but since it only works for Bash I'm not gonna add it to the docs.
