### ISSUE TITLE
Feat: Repurposing & more documentation beyond the API

### ISSUE THREAD

**Issue by Codycody31** [discuitnet/docs#22]
Currently the documentation is primarily focused on the API. However I believe it should be moved around early on to allow the addition of further pages for things such as: building the application, project arch, building/using docker for discuit, and other relevant information for learning how Discuit works or helping develop it, etc.

## Things to be discussed

- How should the file structure be for this? ie: maybe move everything down to `/api` and name the section `The API`
- whatever else comes to mind

**Comment by noClaps** [comment]
I'm not opposed to this, but I think this should be done after we're fully caught up with the API. Also, a lot of the information here is already in the Discuit repository README, so I don't really see a point in duplicating that just yet, unless there's something else to add.

**Comment by Codycody31** [comment]
yeah I do think focusing on the API would be the first and foremost task. The main reason that I'd want the information here is we could have more in-depth explanations and better documentation supporting a wider variety of info (building on different systems, etc). Though I believe this could be further discussed after we have fully completed the API docs as the other things I wish to add are mainly for building local and docker.

**Comment by Codycody31** [comment]
yeah, I can do that, though it will only be for Ubuntu/Debian systems but that should be good enough. I can probably start working on it this friday

**Comment by noClaps** [comment]
I'll close this issue as completed now that #34 has been merged.
