### ISSUE TITLE
[ERROR] Authentication page small typo

### ISSUE THREAD

**Issue by MarkMoretto** [discuitnet/docs#24]
### Where is the error?

On the [Authentication page](https://docs.discuit.net/authentication), the second example for posting to `_login` doesn't use https protocol.

### Correction

Add an `s` to `http` within the first line of the second curl example on the [Authentication page](https://docs.discuit.net/authentication).  

Current:  

```bash
curl 'http://discuit.net/api/_login' -XPOST \
-H 'Cookie: SID=GyzghHpzr3vOdUG2pOoEeqRBFKwbVWBw5Ovy' \
-H 'X-Csrf-Token: FcVgW9FZD8w3iptTeh-Nm3cWm4QjVXYulKjqMWjSJkg=' \
-d '{"username":"neo","password":"whatever"}'
```  

Proposed change:  

```bash
curl 'https://discuit.net/api/_login' -XPOST \
-H 'Cookie: SID=GyzghHpzr3vOdUG2pOoEeqRBFKwbVWBw5Ovy' \
-H 'X-Csrf-Token: FcVgW9FZD8w3iptTeh-Nm3cWm4QjVXYulKjqMWjSJkg=' \
-d '{"username":"neo","password":"whatever"}'
```

### Would you like to work on this?

- [ ] I would like to work on this.

**Comment by noClaps** [comment]
Yeah this looks good to me, you can check the box if you wanna make a PR for this. If not, that's okay, I can make one.

**Comment by MarkMoretto** [comment]
Ok.

I just want to note that you're doing a great job, @noClaps.  Thanks for all the quick responses and feedback.

**Comment by MarkMoretto** [comment]
I have another question:

For posts, the ultimate final timestamp for a post and any activity for related comments would be the `lastActivityAt` field in the [Post type](https://docs.discuit.net/types#post), correct?

**Comment by noClaps** [comment]
Yes. The `lastActivityAt` field gives you the last timestamp any activity occurred on that post. If the post has no comments, then it would be the time that the post was posted, otherwise it would be the time that the most recent comment was left on the post.

**Comment by noClaps** [comment]
Since this issue is fixed now, I'll close it.
