### ISSUE TITLE
[ERROR] `Post` object documentation and implementation don't match each other

### ISSUE THREAD

**Issue by reallytiredofclowns** [discuitnet/docs#26]
### Have you read the contributing guidelines?

- [X] I have read the contributing guidelines.

### Where is the error?

https://docs.discuit.net/types#post and/or the related Discuit site code.

### Correction

Apologies as, again, since the documentation and the implementation are in conflict, I don't know what is correct.

These fields are in the documentation, but do not seem to be returned (reliably) by the API.

* `deletedBy`: can't see this returned on user- or mod-deleted posts.
* `lockedByGroup` key is not always present; confusing if the documentation says `null` is a possible value. Seems to be returned only if the post is actually locked.
* `link` seems to be a returned key only if it is a link post; documentation is unclear--"only valid for link posts" means the key is only present for link posts? But `null` is listed as a possible return value.
* `deletedContentAs`: possibly admins only? I can't seem to see this returned anywhere.
* `deletedAs` is implied in the documentation as always present, even if only as `null`, but is not returned as a key in all cases. My guess is that it is only present as a key when the post was in fact deleted. Compare https://discuit.net/api/posts/9l5Om_AV (not deleted, does not have `deletedAs` key) with https://discuit.net/api/posts/I0G0VuEi (`deletedAs` is "mods").

These fields are in the response, but are not documented:

* `communityBannerImage`: appears to be data associated with the disc's banner image.
* `isCommunityMuted`: old docs probably predate the implementation of this site function.
* `isAuthorMuted`: old docs probably predate the implementation of this site function.
* `isPinnedSite`: old docs probably predate the implementation of this site function.
*  `image`: old docs probably predate the implementation of this site function; appears to be data associated with image posts.
*  `author`: appears to be a `User` object, which is a can of worms to open another day.

### Would you like to work on this?

- [ ] I would like to work on this.

**Comment by noClaps** [comment]
> Apologies as, again, since the documentation and the implementation are in conflict, I don't know what is correct.

The implementation is generally correct, so if you're looking to use something you'd wanna refer to that. I'll have a look at it tomorrow, and update the docs. Thanks again!

**Comment by reallytiredofclowns** [comment]
I won't have a lot of time until the weekend, but a cursory glance found [a minor typo which I've marked](https://github.com/discuitnet/docs/pull/28/files#r1570942162). I'm... not approving and not disapproving, but I think it's a net benefit to publish the update now since it fleshes out the documentation. If anything turns out to be wrong it can be updated again.

**Comment by noClaps** [comment]
Okay, I'll merge it in, and if there's anything else you can open a new issue for it. I think the PR does update the Post type to match the current implementation well enough that this issue can be closed. As I mentioned, I'll make a separate PR to add the Image and Link types, and update the other types as needed.
