### ISSUE TITLE
How does the `ImageFit` value work for `ImageCopy`?

### ISSUE THREAD

**Issue by noClaps** [discuitnet/docs#29]
I can see [here](https://github.com/discuitnet/discuit/blob/1ebf2d67a8a0fbc04eac8095fdb959d3a1f900b4/internal/images/record.go#L287) that the `ImageCopy` struct has a value called `Fit`, which is implemented [here](https://github.com/discuitnet/discuit/blob/1ebf2d67a8a0fbc04eac8095fdb959d3a1f900b4/internal/images/images.go#L296) as `ImageFit`. It looks like it can only be one of two values: "cover" and "contain", defaulting to "contain". However, I'm not sure what the difference is here, and what this value is actually doing. Also, none of the default communities' banner images' or profile pictures' copies have the "contain" value, so I'm not sure where this is even used.

@previnder

**Comment by Codycody31** [comment]
Cover: `ImageFitCover covers the given container with the image. The resulting image may be shrunken, enlarged, and/or cropped.`
Contain: `ImageFitContain fits the image in the container without either enlarging the image or cropping it`. Also, it appears the `contain` value is used for image posts and the user's profile picture.

**Comment by noClaps** [comment]
Yes, but those are both CSS properties that can be set on the frontend, what are they doing in the API?

**Comment by Codycody31** [comment]
I think it actually generates the image, at least that is what I can tell from here: 

https://github.com/discuitnet/discuit/blob/f6fc5b6aef8f224cf8b71551e430b4965921fb8c/internal/images/images.go#L785-L861

**Comment by noClaps** [comment]
So I assume it's supposed to be used with the corresponding value for the `object-fit` property? I guess that makes sense, I'll add a line about it in the docs.
