### ISSUE TITLE
[SUGGEST] Add notification types

### ISSUE THREAD

**Issue by noClaps** [discuitnet/docs#32]
### Have you read the contributing guidelines?

- [X] I have read the contributing guidelines.

### What is your suggestion?

Currently, the [Notification type](https://docs.discuit.net/types#notification) only has an empty object for the `notif` value. This should be updated to show the different possible notification types by analysing the API requests made by the Discuit client.

### Would you like to work on this?

- [ ] I would like to work on this.

**Comment by ttaylor-st** [comment]
Working on this now, what would be the best way for me to put this into the docs? Just new types under the [Notification type](https://docs.discuit.net/api/types#notification) section?

**Comment by noClaps** [comment]
Yeah, that works, and you can also update the `notif` object in the `Notification` type.

You can add them as new types within the same code block, like how `ImageCopy` is in the [Image type](https://docs.discuit.net/api/types#image), or in separate code blocks if it's a lot of them. I'll review the PR anyway to make sure it makes sense and looks easily readable.
