### ISSUE TITLE
[ERROR] Self-Hosting Steps

### ISSUE THREAD

**Issue by MarkMoretto** [discuitnet/docs#35]
### Have you read the contributing guidelines?

- [X] I have read the contributing guidelines.

### Where is the error?

On the [self-hosting](https://github.com/discuitnet/docs/blob/main/docs/self-hosting.md) page.

### Correction

Couple points: 

1. Having Git installed is not listed as a prerequisite.
2. Under the [Running with Docker](https://docs.discuit.net/self-hosting#running-with-docker) section, the first step is "Build the Docker Image."  What Docker image?  Adding some additional detail here might help.
3. Would it make sense to add linkage? For example, here's a linked version of [config.default.yaml](https://github.com/discuitnet/discuit/blob/main/config.default.yaml).

### Would you like to work on this?

- [ ] I would like to work on this.

**Comment by noClaps** [comment]
> Having Git installed is not listed as a prerequisite.

Git is not a dependency of Discuit, and most Linux systems have it pre-installed anyway. I think most people should be able to figure out that they'd need to get the repository somehow.

> Under the [Running with Docker](https://docs.discuit.net/self-hosting#running-with-docker) section, the first step is "Build the Docker Image." What Docker image? Adding some additional detail here might help.

@Codycody31 will be able to explain this part better.

> Would it make sense to add linkage? For example, here's a linked version of [config.default.yaml](https://github.com/discuitnet/discuit/blob/main/config.default.yaml).

I must have missed this in the original PR, thanks for pointing it out! I can make a PR for this, or @Codycody31 can do it if the Docker image explanation needs additional clarification too.

**Comment by Codycody31** [comment]
> What Docker image? Adding some additional detail here might help.

It would be building the docker image discuit, however I didn't have instructions for git in that section, so the PR will also fix that by moving it up to above everything else. Let me know in the PR if their is any other things I could have added linkage to that I missed.

**Comment by MarkMoretto** [comment]
Cheers.  I hope my comments don't come across as a personal attack or anything.  I'm just trying to help out a bit :-)

**Comment by noClaps** [comment]
Not at all! You pointed out exactly what was missing and where, it's very helpful!

**Comment by MarkMoretto** [comment]
Just as a side note:

> I think most people should be able to figure out that they'd need to get the repository somehow.

Yes, and git isn't a hard requirement, like you mentioned, because users can also download a zip archive of Discuit from GitHub, unpack it, change into it, and run with Docker under the second series of steps noted in the documentation.  I rarely assume anything about end users, which is why having extra detail doesn't hurt.

But, it is your documentation and I leave any decision up to you. :smile:
