### ISSUE TITLE
`/communities` vs `/communities/{communityId}` clarification

### ISSUE THREAD

**Issue by reallytiredofclowns** [discuitnet/docs#4]
Both of these endpoints specify the return one or more `community` objects. However, the data returned is different. I believe (?) this may be working as intended since the presumed use case for `/communities` is for populating a large list of discs and may not need as much detailed information as retrieving a specific disc. However, it's possible to use both endpoints to retrieve a single disc, and the difference is confusing.

`https://discuit.net/api/communities?q=general` returns a fairly short JSON response.  Various of the fields are returned as `null`, including `mods`, `rules`, and `ReportDetails`.

`https://discuit.net/api/communities/general?byName=true` returns a more detailed JSON response, with `mods` and `rules` populated; I assume `ReportDetails` remains `null` because I do not have mod powers in the disc.

If this is working as intended, there should be an explanation of this difference in the endpoint pages or the `Types` page.

[edit: spelling]

**Comment by Codycody31** [comment]
I believe the `/api/communities/{id}` should never return more than one, its basically selecting off the unique id or name of the community. While `/api/communities` is for bulk numbers, ie: home page, and other things, and with this it doesn't need as much info provided to the caller.

**Comment by noClaps** [comment]
@Codycody31 Would you like to make a PR explaining that? I think a brief explanation on the [`/communities` endpoint page](https://docs.discuit.net/endpoints/communities/communities) should be enough.

**Comment by Codycody31** [comment]
Yeah, I should be able to do that
