### ISSUE TITLE
[ERROR] Slightly confusing terminology in Types -> Comment

### ISSUE THREAD

**Issue by DiscuitFelix30** [discuitnet/docs#6]
### Where is the error?

[In the Comment section of the Types page](https://docs.discuit.net/types#comment)

### Correction

Clarification regarding what "direct replies" and "direct ancestor comments" might be useful. The way I'm interpreting it right now is:

- "Direct replies" is the replies to a comment with a depth 1 higher than the comment itself, and only the ones nested under that exact comment. (I'm interpreting it like this because there are also non-direct replies, which I'm assuming means replies that are more than 1 depth higher)
- "Direct ancestor comments" is all ancestors that the comment is nested in. (I'm interpreting it like this because it says it starts at the top-most comment, implying multiple ancestor IDs can be provided)

The meaning of "direct" seems to be slightly different in each instance, or at least I'm interpreting them differently.

### Would you like to work on this?

- [ ] I would like to work on this.

**Comment by noClaps** [comment]
I think the correct terminology for this would be "ancestor comments" instead of "direct ancestor comments". It starts from the 0 depth comment and works its way down to the current comment, without including it. The direct ancestor would be the immediate parent comment.
